namespace Helpers
{
    public static class Data
    {
        public static string[] Keywords = {
            "Azure",
            "Microsoft",
            "Cloud Computing",
            "Devops",
            "nodeJs",
            "Big Data",
            "IOT",
            "Mobile Development",
            "Software Development",
            "Information Technology",
            "SaaS (Software as a Service)",
            "System Administartion",
            "javasript",
            "Project Spark",
            "Internet of Things",
            "IOS Development",
            "Visual Studio",
            "IT Professionals",
            "IaaS (Infrastructure as a Service)",
            "Configuration Management",
            "HTML5",
            "Data Analytics",
            "Smart Sensors",
            "Android Development",
            ".Net",
            "New Technology",
            "PaaS (Platform as a Service)",
            "Continuous Delivery",
            "AngularJS",
            "NoSql",
            "Arduino",
            "Mobile Technology",
            "ASP.NET",
            "Information Technology Leadership",
            "AWS",
            "Virtualization",
            "Jquery",
            "mongoDB",
            "Robotics",
            "Game Development",
            "computer programming",
            "Technology Professionals",
            "Amazon Web Services",
            "ruby",
            "Machine Learning",
            "programming languages",
            "Software engineering",
            "php",
            "Hadoop",
            "Microsoft Azure",
            "python",
            "MapReduce",
            "docker",
            "Ruby on Rails",
            "Java",
            "Web Dev",
            "Web Development",
            "AWS",
            "Google Cloud" };

        public static string[] Influencers = {"alipruebas", "fingerpaintapp" , "JorgeCasar", "Etnasoft", "carlosazaustre", "CKGrafico","jjmerelo"  };

    }
}
